# Generated by Django 5.1.2 on 2024-11-28 05:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('content_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M2MComentsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.content')),
                ('coment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comments.comments')),
            ],
        ),
    ]
