# Generated by Django 5.1.2 on 2024-11-28 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0001_initial'),
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='blog',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='Content.content'),
            preserve_default=False,
        ),
    ]
