# Generated by Django 5.1.2 on 2024-11-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0002_images_name_images_size_images_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='url',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
